# Generated by Django 4.0.5 on 2022-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Артикль'),
        ),
    ]
